services:
  postgres:
    image: postgres:15.3
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB = ${POSTGRES_DB}
      - POSTGRES_USER =${DBUSER}
      - POSTGRES_PASSWORD = ${DBPASSWORD}
    ports:
      - "5555:5432"

  nats:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"
